CREATE TABLE public.mentorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  type text NOT NULL DEFAULT 'individual',
  duration text NOT NULL DEFAULT '',
  sessions text NOT NULL DEFAULT '',
  rating numeric NOT NULL DEFAULT 0,
  price text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  includes text[] NOT NULL DEFAULT '{}',
  cta_link text NOT NULL DEFAULT 'https://wa.me/5500000000000',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.mentorias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read mentorias" ON public.mentorias FOR SELECT USING (true);
CREATE POLICY "Admins can insert mentorias" ON public.mentorias FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins can update mentorias" ON public.mentorias FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins can delete mentorias" ON public.mentorias FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));